# Generated by Django 4.1.3 on 2022-11-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=99999)),
                ('uuid', models.CharField(max_length=99)),
            ],
        ),
    ]
